In [1]:
import numpy as np

In [74]:
day4_input = np.genfromtxt('..\\data\\day4_input.txt', dtype='str', delimiter='\\n\\n')


draws = np.array(day4_input[0].split(',')).astype('int')
print (draws, len(draws))
num_boards = int((len(day4_input) -1) / 5)
print (num_boards)

boards = np.zeros((num_boards,5,5), dtype=int)
board_mask = np.zeros((num_boards,5,5),dtype=int)

for board in range(num_boards):
    #print (day4_input[board*5 + 1].astype('str').dtype)
    #print (np.char.split(day4_input[board*5 +1]).dtype)
    first_row = np.array(day4_input[board*5+1].split()).astype('int')
    second_row = np.array(day4_input[board*5+2].split()).astype('int')
    third_row = np.array(day4_input[board*5+3].split()).astype('int')
    fourth_row = np.array(day4_input[board*5+4].split()).astype('int')
    fifth_row = np.array(day4_input[board*5+5].split()).astype('int')
    boards[board,0,:] = first_row
    boards[board,1,:] = second_row
    boards[board,2,:] = third_row
    boards[board,3,:] = fourth_row
    boards[board,4,:] = fifth_row



for draw in draws:
    draw_match = np.where(boards == draw)
    board_mask[draw_match] = 1

    dir1 = np.sum(board_mask, axis=1)
    dir2 = np.sum(board_mask, axis=2)

    if ((np.max(dir1) == 5) | (np.max(dir2) == 5)):
        if (np.max(dir1) == 5):
            winning = np.where(dir1 == 5)
        if (np.max(dir2) == 5):
            winning = np.where(dir2 == 5)   

        board_masked= np.ma.array(boards[winning[0],::], mask=board_mask[winning[0],::])   
        sum = board_masked.sum()
        score = sum * draw
        print (score)
        break

    



[30 35  8  2 39 37 72  7 81 41 25 46 56 18 89 70  0 15 84 75 88 67 42 44
 94 71 79 65 58 52 96 83 54 29 14 95 66 61 97 68 57 90 55 32 17 47 20 98
  1 69 63 62 31 86 77 85 87 93 26 40 24 19 48 76 73 49 34 45 82 22 80 78
 23  6 59 91 64 43 21 51 13  3 53 99  4 28 33 74 12  9 36 50 60 11 27 10
  5 16 92 38] 100
100
54275


In [82]:
board_bust = 0
board_mask = np.zeros((num_boards,5,5),dtype=int)

print (boards.shape)

active_boards = boards

for draw in draws:
    draw_match = np.where(active_boards == draw)
    board_mask[draw_match] = 1

    dir1 = np.sum(board_mask, axis=1)
    dir2 = np.sum(board_mask, axis=2)

    dir1 = np.sum(board_mask, axis=1)
    dir2 = np.sum(board_mask, axis=2)

    busted_dir1 = np.where(dir1  == 5)
    busted_dir2 = np.where(dir2 == 5)


    if ((active_boards.shape[0] == 1) & ((np.max(dir1) == 5) | (np.max(dir2) == 5))):
        print ('Final winner', draw)
        print (active_boards)

        board_masked= np.ma.array(active_boards, mask=board_mask)   
        print (board_masked)
        sum = board_masked.sum()
        score = sum*draw
        print (score)
        break
        


    if ((len(busted_dir1[0]) >= 1) | (len(busted_dir2[0]) >=1 )):
        #print (busted_dir1[0], busted_dir2[0])
        all_busts = np.unique(np.concatenate((busted_dir1[0],busted_dir2[0])))
        #print (all_busts, len(active_boards))
        active_boards = np.delete(active_boards, all_busts, axis=0)
        board_mask = np.delete(board_mask, all_busts, axis=0 )




    







(100, 5, 5)
Final winner 51
[[[91 60 47 93 54]
  [69 70 66 85 74]
  [61  5  9 37 40]
  [51 99 42 82 26]
  [84 30 19 11 75]]]
[[[-- 60 -- -- --]
  [-- -- -- -- 74]
  [-- 5 9 -- --]
  [-- 99 -- -- --]
  [-- -- -- 11 --]]]
13158


[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
