In [2]:
import numpy as np

In [74]:
day4_input = np.genfromtxt('..\\data\\day4_test.txt', dtype='str', delimiter='\\n\\n')
print (day4_input)
print (day4_input.dtype)

draws = np.array(day4_input[0].split(',')).astype('int')
num_boards = int((len(day4_input) -1) / 5)

boards = np.zeros((num_boards,5,5), dtype=int)
board_mask = np.zeros((num_boards,5,5),dtype=int)

for board in range(num_boards):
    #print (day4_input[board*5 + 1].astype('str').dtype)
    #print (np.char.split(day4_input[board*5 +1]).dtype)
    first_row = np.array(day4_input[board*5+1].split()).astype('int')
    second_row = np.array(day4_input[board*5+2].split()).astype('int')
    third_row = np.array(day4_input[board*5+3].split()).astype('int')
    fourth_row = np.array(day4_input[board*5+4].split()).astype('int')
    fifth_row = np.array(day4_input[board*5+5].split()).astype('int')
    boards[board,0,:] = first_row
    boards[board,1,:] = second_row
    boards[board,2,:] = third_row
    boards[board,3,:] = fourth_row
    boards[board,4,:] = fifth_row


print (boards.shape)

for draw in draws:
    draw_match = np.where(boards == draw)
    board_mask[draw_match] = 1

    dir1 = np.sum(board_mask, axis=1)
    dir2 = np.sum(board_mask, axis=2)

    if ((np.max(dir1) == 5) | (np.max(dir2) == 5)):
        print (draw) 
        if (np.max(dir1) == 5):
            print (np.where(np.max(dir1) == 5, dir1))
        if (np.max(dir2) == 5):
            print (np.where(np.max(dir2) == 5),dir2)       
        break

    



['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1'
 '22 13 17 11  0' '8  2 23  4 24' '21  9 14 16  7' '6 10  3 18  5'
 '1 12 20 15 19' '3 15  0  2 22' '9 18 13 17  5' '19  8  7 25 23'
 '20 11 10 24  4' '14 21 16 12  6' '14 21 17 24  4' '10 16 15  9 19'
 '18  8 23 26 20' '22 11 13  6  5' '2  0 12  3  7']
<U70
(3, 5, 5)
24
(array([0], dtype=int64),) [[3 4 4 1 0]
 [2 3 2 3 2]
 [5 1 1 2 3]]


[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
