In [2]:
import numpy as np


In [21]:
day5_input = np.genfromtxt('..\\data\\day5_input.txt', dtype='str', delimiter='//n')

list2, list3 = map(list, zip(*(x.split('->') for x in day5_input)))


x1,y1 = map(list, zip(*(x.split(',') for x in list2)))
x2,y2 = map(list, zip(*(x.split(',') for x in list3)))
x1=np.array(x1, dtype=int)
x2=np.array(x2, dtype=int)
y1=np.array(y1, dtype=int)
y2=np.array(y2, dtype=int)

xmax = np.max([np.max(x1), np.max(x2)])
ymax = np.max([np.max(y1), np.max(y2)])


check_array = np.zeros((xmax+1, ymax+1))

for index in range(len(x1)):
    xstart = x1[index] 
    xend = x2[index]
    ystart = y1[index]
    yend = y2[index]
    if ((xstart == xend) | (ystart == yend)):
        xmin = np.min([xstart, xend])
        xmax = np.max([xstart, xend])
        ymin = np.min([ystart, yend])
        ymax = np.max([ystart, yend])
        if (xmin == xmax):
            check_array[xmin,ymin:ymax+1] = check_array[xmin,ymin:ymax+1] + 1.
        if (ymin == ymax):
            check_array[xmin:xmax+1,ymin] = check_array[xmin:xmax+1,ymin] + 1.


count = np.count_nonzero(check_array > 1)
print (count)

7085


In [61]:

day5_input = np.genfromtxt('..\\data\\day5_input.txt', dtype='str', delimiter='//n')

list2, list3 = map(list, zip(*(x.split('->') for x in day5_input)))


x1,y1 = map(list, zip(*(x.split(',') for x in list2)))
x2,y2 = map(list, zip(*(x.split(',') for x in list3)))
x1=np.array(x1, dtype=int)
x2=np.array(x2, dtype=int)
y1=np.array(y1, dtype=int)
y2=np.array(y2, dtype=int)

xmax = np.max([np.max(x1), np.max(x2)])
ymax = np.max([np.max(y1), np.max(y2)])


check_array = np.zeros((xmax+1, ymax+1))

print (check_array.shape)

for index in range(len(x1)):
    xstart = x1[index] 
    xend = x2[index]
    ystart = y1[index]
    yend = y2[index]

    xmin = np.min([xstart, xend])
    xmax = np.max([xstart, xend])
    ymin = np.min([ystart, yend])
    ymax = np.max([ystart, yend])

    if ((xstart == xend) | (ystart == yend)):    
        if (xmin == xmax):
            check_array[xmin,ymin:ymax+1] = check_array[xmin,ymin:ymax+1] + 1.
        if (ymin == ymax):
            check_array[xmin:xmax+1,ymin] = check_array[xmin:xmax+1,ymin] + 1.

    else:
        if (xend > xstart):
            new_x = np.arange(xstart, xend+1)
        if (xend < xstart):
            new_x = np.arange(xend, xstart+1)
            new_x = new_x[::-1]
        if (yend > ystart):
            new_y = np.arange(ystart, yend+1)
        if (yend < ystart):
            new_y =np.arange(yend, ystart+1)
            new_y = new_y[::-1]

        for line_el in range(len(new_x)):
            check_array[new_x[line_el], new_y[line_el]] = check_array[new_x[line_el], new_y[line_el]] +1


count = np.count_nonzero(check_array > 1)
print (count)

(990, 990)
20271


In [40]:
print (check_array)

[[1. 0. 0. 0. 0. 0. 0. 1. 0. 2.]
 [1. 0. 0. 0. 1. 0. 1. 0. 0. 2.]
 [1. 2. 1. 0. 1. 1. 0. 0. 0. 2.]
 [0. 1. 1. 0. 3. 0. 0. 0. 0. 1.]
 [0. 0. 1. 2. 1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 1. 3. 0. 0. 0. 0. 1.]
 [0. 1. 0. 1. 2. 1. 0. 0. 0. 0.]
 [2. 1. 2. 1. 2. 0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
